/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author uniflualves
 */
public class TelaMenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_textBemVindo = new javax.swing.JLabel();
        lbl_nomeUsuario = new javax.swing.JLabel();

        lbl_textBemVindo.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
        lbl_textBemVindo.setText("Bem Vindo!");

        lbl_nomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
        lbl_nomeUsuario.setText("a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lbl_textBemVindo)
                .addGap(50, 50, 50)
                .addComponent(lbl_nomeUsuario)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_textBemVindo)
                    .addComponent(lbl_nomeUsuario))
                .addContainerGap(421, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_nomeUsuario;
    private javax.swing.JLabel lbl_textBemVindo;
    // End of variables declaration//GEN-END:variables
}
