/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleLogado;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Usuario;

/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaPrincipal(Usuario usuario) {
        initComponents();
        lbl_usuarioLogado.setText((usuario.getNome()));
        cl = new ControleLogado(this, usuario);
    }
    
    private ControleLogado cl;

    public static Logger getLogger() {
        return logger;
    }

    public ControleLogado getCl() {
        return cl;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getLbl_usuarioLogado() {
        return lbl_usuarioLogado;
    }

    public JPanel getPainelCardPrincipal() {
        return painelCardPrincipal;
    }

    public JPanel getTelaMenuPrincipal() {
        return telaMenuPrincipal;
    }

    public void setCl(ControleLogado cl) {
        this.cl = cl;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setLbl_usuarioLogado(JLabel lbl_usuarioLogado) {
        this.lbl_usuarioLogado = lbl_usuarioLogado;
    }

    public void setPainelCardPrincipal(JPanel painelCardPrincipal) {
        this.painelCardPrincipal = painelCardPrincipal;
    }

    public void setTelaMenuPrincipal(JPanel telaMenuPrincipal) {
        this.telaMenuPrincipal = telaMenuPrincipal;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCardPrincipal = new javax.swing.JPanel();
        telaMenuPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_usuarioLogado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCardPrincipal.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
        jLabel1.setText("Bem Vindo");

        lbl_usuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N

        javax.swing.GroupLayout telaMenuPrincipalLayout = new javax.swing.GroupLayout(telaMenuPrincipal);
        telaMenuPrincipal.setLayout(telaMenuPrincipalLayout);
        telaMenuPrincipalLayout.setHorizontalGroup(
            telaMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMenuPrincipalLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(lbl_usuarioLogado)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        telaMenuPrincipalLayout.setVerticalGroup(
            telaMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaMenuPrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(telaMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_usuarioLogado))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        painelCardPrincipal.add(telaMenuPrincipal, "menuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_usuarioLogado;
    private javax.swing.JPanel painelCardPrincipal;
    private javax.swing.JPanel telaMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
