/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ControleTrocarTela;
import controller.ControleCadastro;
import controller.ControleLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author uniflualves
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        ci = new ControleTrocarTela(this);
        cc = new ControleCadastro(this);
        cl = new ControleLogin(this);
    }
    
    private ControleTrocarTela ci;
    private ControleCadastro cc;
    private ControleLogin cl;

   public JPanel getPainelInicio(){
       return painelInicio;
   }

    public JButton getBt_cadastro() {
        return bt_cadastro;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public JLabel getLbl_senha() {
        return lbl_senha;
    }

    public JPanel getTelaCadastro() {
        return telaCadastro;
    }

    public JPanel getTelaLogin() {
        return telaLogin;
    }

    public JPanel getTelaMenu() {
        return telaInicio;
    }
    
    public JTextField getTxt_usuarioNome(){
        return txt_usuarioNome;
    }

    public JTextField getTxt_nome() {
        return txt_nome;
    }

    public JTextField getTxt_senha() {
        return txt_senha;
    }
    
    public JTextField getTxt_usuarioLogin(){
        return txt_usuarioLogin;
    }
    
    public JTextField getTxt_senhaLogin(){
        return txt_senhaLogin;
    }
    
    

    public void setBt_cadastro(JButton bt_cadastro) {
        this.bt_cadastro = bt_cadastro;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }

    public void setLbl_senha(JLabel lbl_senha) {
        this.lbl_senha = lbl_senha;
    }

    public void setPainelInicio(JPanel painelInicio) {
        this.painelInicio = painelInicio;
    }

    public void setTelaCadastro(JPanel telaCadastro) {
        this.telaCadastro = telaCadastro;
    }

    public void setTelaLogin(JPanel telaLogin) {
        this.telaLogin = telaLogin;
    }

    public void setTelaMenu(JPanel telaMenu) {
        this.telaInicio = telaMenu;
    }
    
    public void setTxt_usuarioNome(JTextField txt_usuarioNome){
        this.txt_usuarioNome = txt_usuarioNome;
    }

    public void setTxt_nome(JTextField txt_nome) {
        this.txt_nome = txt_nome;
    }

    public void setTxt_senha(JTextField txt_senha) {
        this.txt_senha = txt_senha;
    }
    
    public void setTxt_usuarioLogin(JTextField txt_usuarioLogin){
        this.txt_usuarioLogin = txt_usuarioLogin;
    }
    
    
    
    public void setTxt_senhaLogin(JTextField txt_senhaLogin){
        this.txt_senhaLogin = txt_senhaLogin;
    }
   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInicio = new javax.swing.JPanel();
        telaInicio = new javax.swing.JPanel();
        bt_cadastro = new javax.swing.JButton();
        bt_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        telaCadastro = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        bt_cadastrar = new javax.swing.JButton();
        txt_usuarioNome = new javax.swing.JTextField();
        lbl_nome1 = new javax.swing.JLabel();
        bt_voltarInicio = new javax.swing.JButton();
        telaLogin = new javax.swing.JPanel();
        txt_usuarioLogin = new javax.swing.JTextField();
        lbl_usuario2 = new javax.swing.JLabel();
        txt_senhaLogin = new javax.swing.JTextField();
        lbl_senha2 = new javax.swing.JLabel();
        bt_logar = new javax.swing.JButton();
        bt_voltarInicio2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 383));

        painelInicio.setLayout(new java.awt.CardLayout());

        bt_cadastro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_cadastro.setText("Cadastro");
        bt_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroActionPerformed(evt);
            }
        });

        bt_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_login.setText("Login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel1.setText("FEI TV");

        javax.swing.GroupLayout telaInicioLayout = new javax.swing.GroupLayout(telaInicio);
        telaInicio.setLayout(telaInicioLayout);
        telaInicioLayout.setHorizontalGroup(
            telaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicioLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(telaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        telaInicioLayout.setVerticalGroup(
            telaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(bt_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        painelInicio.add(telaInicio, "inicio");

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nome.setText("Nome de Exibição");

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_senha.setText("Senha");
        lbl_senha.setToolTipText("");

        bt_cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });

        txt_usuarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioNomeActionPerformed(evt);
            }
        });

        lbl_nome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nome1.setText("Usuário");

        bt_voltarInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_voltarInicio.setText("Voltar");
        bt_voltarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroLayout = new javax.swing.GroupLayout(telaCadastro);
        telaCadastro.setLayout(telaCadastroLayout);
        telaCadastroLayout.setHorizontalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(bt_cadastrar))
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_senha)
                            .addComponent(lbl_nome1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_usuarioNome, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(txt_nome))
                            .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_voltarInicio))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        telaCadastroLayout.setVerticalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome1)
                    .addComponent(txt_usuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(bt_cadastrar)
                .addGap(57, 57, 57)
                .addComponent(bt_voltarInicio)
                .addGap(46, 46, 46))
        );

        painelInicio.add(telaCadastro, "cadastro");

        lbl_usuario2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_usuario2.setText("Usuario");
        lbl_usuario2.setToolTipText("");

        lbl_senha2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_senha2.setText("Senha");
        lbl_senha2.setToolTipText("");

        bt_logar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_logar.setText("Entrar");
        bt_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logarActionPerformed(evt);
            }
        });

        bt_voltarInicio2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_voltarInicio2.setText("Voltar");
        bt_voltarInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarInicio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaLoginLayout = new javax.swing.GroupLayout(telaLogin);
        telaLogin.setLayout(telaLoginLayout);
        telaLoginLayout.setHorizontalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(telaLoginLayout.createSequentialGroup()
                                .addComponent(lbl_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(telaLoginLayout.createSequentialGroup()
                                .addComponent(lbl_senha2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_senhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bt_voltarInicio2)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        telaLoginLayout.setVerticalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_senhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addComponent(lbl_senha2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(55, 55, 55)
                .addComponent(bt_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_voltarInicio2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        painelInicio.add(telaLogin, "login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroActionPerformed
        ci.trocarCadastro();
    }//GEN-LAST:event_bt_cadastroActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        String usuarioNome = this.getTxt_usuarioNome().getText();
        String nome = this.getTxt_nome().getText();
        String senha = this.getTxt_senha().getText();
        cc.salvarUsuario(usuarioNome, nome, senha);
        
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        ci.trocarLogin();
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_voltarInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarInicio2ActionPerformed
        ci.trocarInicio();
    }//GEN-LAST:event_bt_voltarInicio2ActionPerformed

    private void bt_voltarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarInicioActionPerformed
        ci.trocarInicio();
    }//GEN-LAST:event_bt_voltarInicioActionPerformed

    private void bt_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logarActionPerformed
        cl.logarUsuario();
    }//GEN-LAST:event_bt_logarActionPerformed

    private void txt_usuarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioNomeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaInicio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_cadastro;
    private javax.swing.JButton bt_logar;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_voltarInicio;
    private javax.swing.JButton bt_voltarInicio2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_nome1;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_senha2;
    private javax.swing.JLabel lbl_usuario2;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JPanel telaCadastro;
    private javax.swing.JPanel telaInicio;
    private javax.swing.JPanel telaLogin;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_senhaLogin;
    private javax.swing.JTextField txt_usuarioLogin;
    private javax.swing.JTextField txt_usuarioNome;
    // End of variables declaration//GEN-END:variables
}
