/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleAlterarLogin;
import controller.ControleTrocarTela;
import controller.ControlePrincipal;
import controller.ControlePesquisar;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import model.Usuario;
/**
 *
 * @author uniflualves
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuario usuario) {
        initComponents();
        lbl_usuarioLogado.setText((usuario.getNome()));
        this.getTxt_novoNome().setText(usuario.getNome());
        cp = new ControlePrincipal(this, usuario);
        cal = new ControleAlterarLogin(this, usuario);
        trocarTela = new ControleTrocarTela(this);
        cPes = new ControlePesquisar(this);
    }
    
    private ControlePrincipal cp;
    private ControleAlterarLogin cal;
    private ControleTrocarTela trocarTela;
    private ControlePesquisar cPes;

    public ControlePrincipal getCp() {
        return cp;
    }

    public ControleAlterarLogin getCal() {
        return cal;
    }

    public ControleTrocarTela getTrocarTela() {
        return trocarTela;
    }

    public JButton getBt_alterarLogin() {
        return bt_alterarTelaLogin;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getLbl_usuarioLogado() {
        return lbl_usuarioLogado;
    }

    public JPanel getPainelAlterarLogin() {
        return painelAlterarLogin;
    }

    public JPanel getPainelCardPrincipal() {
        return painelCardPrincipal;
    }

    public JPanel getPainelMenuPrincipal() {
        return painelMenuPrincipal;
    }

    public JTextField getTxt_novaSenha() {
        return txt_novaSenha;
    }

    public JTextField getTxt_novoNome() {
        return txt_novoNome;
    }

    public JTextField getTxt_pesquisa() {
        return txt_pesquisa;
    }
    
    
    
    

    public void setCp(ControlePrincipal cp) {
        this.cp = cp;
    }

    public void setCal(ControleAlterarLogin cal) {
        this.cal = cal;
    }

    public void setTrocarTela(ControleTrocarTela trocarTela) {
        this.trocarTela = trocarTela;
    }

    public void setBt_alterarLogin(JButton bt_alterarLogin) {
        this.bt_alterarTelaLogin = bt_alterarLogin;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setLbl_usuarioLogado(JLabel lbl_usuarioLogado) {
        this.lbl_usuarioLogado = lbl_usuarioLogado;
    }

    public void setPainelAlterarLogin(JPanel painelAlterarLogin) {
        this.painelAlterarLogin = painelAlterarLogin;
    }

    public void setPainelCardPrincipal(JPanel painelCardPrincipal) {
        this.painelCardPrincipal = painelCardPrincipal;
    }

    public void setPainelMenuPrincipal(JPanel painelMenuPrincipal) {
        this.painelMenuPrincipal = painelMenuPrincipal;
    }

    public void setTxt_novaSenha(JTextField txt_novaSenha) {
        this.txt_novaSenha = txt_novaSenha;
    }

    public void setTxt_novoNome(JTextField txt_novoNome) {
        this.txt_novoNome = txt_novoNome;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCardPrincipal = new javax.swing.JPanel();
        painelMenuPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_usuarioLogado = new javax.swing.JLabel();
        bt_alterarTelaLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        painelAlterarLogin = new javax.swing.JPanel();
        txt_novoNome = new javax.swing.JTextField();
        lbl_novoNome = new javax.swing.JLabel();
        lbl_novaSenha = new javax.swing.JLabel();
        txt_novaSenha = new javax.swing.JTextField();
        bt_alterar = new javax.swing.JButton();
        bt_voltarMenu = new javax.swing.JButton();
        painelPesquisar = new javax.swing.JPanel();
        txt_pesquisa = new javax.swing.JTextField();
        bt_voltarMenu2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCardPrincipal.setLayout(new java.awt.CardLayout());

        painelMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel1.setText("Bem Vindo");

        lbl_usuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N

        bt_alterarTelaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_alterarTelaLogin.setText("Alterar Login");
        bt_alterarTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarTelaLoginActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMenuPrincipalLayout = new javax.swing.GroupLayout(painelMenuPrincipal);
        painelMenuPrincipal.setLayout(painelMenuPrincipalLayout);
        painelMenuPrincipalLayout.setHorizontalGroup(
            painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addComponent(lbl_usuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(bt_alterarTelaLogin)
                .addContainerGap())
        );
        painelMenuPrincipalLayout.setVerticalGroup(
            painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbl_usuarioLogado)))
                    .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_alterarTelaLogin)))
                .addGap(109, 109, 109)
                .addComponent(jButton1)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        painelCardPrincipal.add(painelMenuPrincipal, "menuPrincipal");

        txt_novoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_novoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_novoNome.setText("Novo Nome:");

        lbl_novaSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_novaSenha.setText("Nova Senha");

        txt_novaSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bt_alterar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_alterar.setText("Alterar Login");
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });

        bt_voltarMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_voltarMenu.setText("Voltar");
        bt_voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAlterarLoginLayout = new javax.swing.GroupLayout(painelAlterarLogin);
        painelAlterarLogin.setLayout(painelAlterarLoginLayout);
        painelAlterarLoginLayout.setHorizontalGroup(
            painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterarLoginLayout.createSequentialGroup()
                .addGroup(painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAlterarLoginLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_novaSenha)
                            .addComponent(lbl_novoNome))
                        .addGap(18, 18, 18)
                        .addGroup(painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_alterar)
                            .addComponent(txt_novoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelAlterarLoginLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(bt_voltarMenu)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        painelAlterarLoginLayout.setVerticalGroup(
            painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterarLoginLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_novoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_novoNome))
                .addGap(18, 18, 18)
                .addGroup(painelAlterarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_novaSenha)
                    .addComponent(txt_novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addComponent(bt_alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(bt_voltarMenu)
                .addGap(78, 78, 78))
        );

        painelCardPrincipal.add(painelAlterarLogin, "telaAlterar");

        txt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisaKeyReleased(evt);
            }
        });

        bt_voltarMenu2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_voltarMenu2.setText("Voltar");
        bt_voltarMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarMenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesquisarLayout = new javax.swing.GroupLayout(painelPesquisar);
        painelPesquisar.setLayout(painelPesquisarLayout);
        painelPesquisarLayout.setHorizontalGroup(
            painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesquisarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bt_voltarMenu2))
                    .addGroup(painelPesquisarLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        painelPesquisarLayout.setVerticalGroup(
            painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(bt_voltarMenu2)
                .addGap(31, 31, 31))
        );

        painelCardPrincipal.add(painelPesquisar, "pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_alterarTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarTelaLoginActionPerformed
        trocarTela.trocarAlterarLogin();
    }//GEN-LAST:event_bt_alterarTelaLoginActionPerformed

    private void bt_voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarMenuActionPerformed
        trocarTela.trocarMenu();
    }//GEN-LAST:event_bt_voltarMenuActionPerformed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        cal.atualizarDados();
        
    }//GEN-LAST:event_bt_alterarActionPerformed

    private void bt_voltarMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarMenu2ActionPerformed
        trocarTela.trocarMenu();
    }//GEN-LAST:event_bt_voltarMenu2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        trocarTela.trocarPesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisaKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cPes.Pesquisar();
        }
    }//GEN-LAST:event_txt_pesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_alterarTelaLogin;
    private javax.swing.JButton bt_voltarMenu;
    private javax.swing.JButton bt_voltarMenu2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_novaSenha;
    private javax.swing.JLabel lbl_novoNome;
    private javax.swing.JLabel lbl_usuarioLogado;
    private javax.swing.JPanel painelAlterarLogin;
    private javax.swing.JPanel painelCardPrincipal;
    private javax.swing.JPanel painelMenuPrincipal;
    private javax.swing.JPanel painelPesquisar;
    private javax.swing.JTextField txt_novaSenha;
    private javax.swing.JTextField txt_novoNome;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
